### ISSUE TITLE
Assemblage et "containerization" de l'application.

### ISSUE THREAD

**Issue by abdorah** [abdorah/Cabinet_Medical#2]
### Proposition des idées pour le deployment de l'application
_En ce qui concerne le deployement de notre application, plusieurs choix se présentent. Or, il faut bien estimer les avantages et les inconvénients_

- Utilisation d'un docker file en se basant sur la version "latest" de tomcat: Ceci permet de bien utiliser l'application. Mais on suppose que celui qui l'utilise a mysql DB avec la même configuration telle que du port, mot de pass utilisateur etc que la notre.
-  Utilisation de docker compose: Certes ceci permet de bien utiliser l'application sans aucun soucis de configuration. Mais, pour utiliser l'application ça necissite d'utiliser les mêmes images docker utiliser pour la composition de l'application qui serant mysql et tomcat.
L'objectif ici est de trouver la bonne méthode pour deployer l'application; Qu'en pensez vous?

**Comment by AybH26** [comment]
Je pense qu'il faut inclure les deux méthodes ensembles. Car d'une part c'est deux méthodes ne sont pas différentes. D'autre part l'utilisation de docker composer ne change rien dans le docker file de la première méthode. Ainsi je pense que c'est mieux d'utiliser docker composer.

**Comment by abdoelhafi** [comment]
Ah vous avez raison! Puisque les deux méthodes son implémentables je pense que c'est mieux de les utilisers tous les deux. Un changement à faire ici est le changement de la version de tomcat en tomcat:8-jdk15 pour le jdk 15.  Aussi il faut ajouter `--net=host` en cas de base de donnée sur la machine host.
